theme: jekyll-theme-slate
title: Ruchita Mahesh Kumar 
description: Computational Neuroscientist 

<a href=“{{ site.baseurl }}/research”>Research</a>
<a href=“{{ site.baseurl }}/”>Blog</a>
<a href=“{{ site.baseurl }}/about”>About</a>
